// <auto-generated />
using System;
using ManjDb.DataModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManjDb.DataModels.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230921190233_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("ManjDb.DataModels.RawData", b =>
                {
                    b.Property<int>("RawDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChildId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FormTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JsonData")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RetrievedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("RawDataId");

                    b.ToTable("RawData");
                });

            modelBuilder.Entity("ManjDb.DataModels.TempChild", b =>
                {
                    b.Property<int>("TempChildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("TempChildId");

                    b.ToTable("TempChildren");
                });
#pragma warning restore 612, 618
        }
    }
}
