// <auto-generated />
using ManjDb.DataModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManjDb.DataModels.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("ManjDb.DataModels.ChildInfo", b =>
                {
                    b.Property<int>("ChildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Allergies")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedAdultsString")
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassroomIdsString")
                        .HasColumnType("TEXT");

                    b.Property<string>("DominantLanguage")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactsString")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstDay")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormsRawJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("HoursString")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastDay")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentIdsString")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePhoto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Program")
                        .HasColumnType("TEXT");

                    b.HasKey("ChildId");

                    b.ToTable("ChildInfos");
                });

            modelBuilder.Entity("ManjDb.DataModels.Classrooms", b =>
                {
                    b.Property<int>("ClassroomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassroomName")
                        .HasColumnType("TEXT");

                    b.Property<int>("LessonSetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .HasColumnType("TEXT");

                    b.HasKey("ClassroomId");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("ManjDb.DataModels.FormTemplateIds", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimalPermissionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApprovedPickupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmergencyInformationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnrollmentContractId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoingOutPermissionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhotoReleaseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FormTemplateIds");
                });
#pragma warning restore 612, 618
        }
    }
}
